LOAD DATA LOCAL INFILE '/home/cs143/shared/tests/test/test.del' INTO TABLE R FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '/home/cs143/shared/tests/test/test2.del' INTO TABLE S FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
