LOAD DATA LOCAL INFILE '/home/cs143/shared/hw2/Employee.del' INTO TABLE Employee FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '/home/cs143/shared/hw2/Company.del' INTO TABLE Company FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '/home/cs143/shared/hw2/Work.del' INTO TABLE Work FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '/home/cs143/shared/hw2/Manage.del' INTO TABLE Manage FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
